services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    volumes:
      - ./apps/api/src:/app/apps/api/src
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - n8n
    networks:
      - shoplift

  n8n:
    image: n8nio/n8n:latest
    restart: always
    networks:
      - shoplift

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - shoplift

networks:
  shoplift:
    driver: bridge
